### PR TITLE
OJS 3.3 compatibility

### PR DESCRIPTION
**Pull request by withanage**
@ewhanson 

Hi  Eric,
for TIB work, I was testing this plugin and had to change small things to make it compatible for OJS 3.3.
If  this would break and you would like create a seperate branch for stable-3_3_0, I will create a seperate PR.

### CODE REVIEW

**Comment by ewhanson** [comment]
Thanks @withanage. 

I'm happy to keep compatibility for 3.3 on the main branch until there are breaking changes for 3.4 added. I also have an open issue for adding in PHP 8.0 support, so I'll have a look at this and that, then get another release ready.

Out of curiosity, were the issues you ran into related to PHP versions or changes in OJS?

**Comment by withanage** [comment]
Thanks @ewhanson 

the changes I made were related to OJS 3.3 compatibility. They were minor. I think PHP 8 compatibility is already there in the plugin

**Comment by ewhanson** [comment]
Thanks again @withanage! All looks good. Would you be able to update the PR to use space instead of tabs? Also a good reminder I should run the whole plugin through the code formatter in OJS to bring its styles in line with the rest of the code base.

**Comment by withanage** [comment]
@ewhanson  , sure, I have changed the indentation to spaces.

**Comment by ewhanson** [comment]
Thanks, @withanage!

**Pull request merged**
